### ISSUE TITLE
PDF generate with plugin, fail occur

### ISSUE THREAD

**Issue by tsuyoshicho** [honkit/honkit#142]
## Summary

I'm using HonKit that use together gitbook-plugin-uml, that reason are plantuml's svg generating needed.

https://github.com/vowstar/gitbook-plugin-uml

That work fine in local Windows.

But now, work in GitHub workflow (and same as in Linux for test) are failed.

Researching it, result: plugin or honkit, generated svg binding miss.

Report it.

- HonKit version:
npx honkit --version
3.6.8

## Step to reproduce

1. In Linux(or GitHub ubuntu-latest vm).
2. npx honkit pdf . output.pdf

- Link to code example:

https://github.com/tsuyoshicho/honkit-gen-sample

## Expected results

Build success for PDF,EPUB.
(in Linux, 1pass work)

## Actual results

Build test result link

### PDF fail test result

- [Release Release v3\.0\.0 · tsuyoshicho/honkit\-gen\-sample](https://github.com/tsuyoshicho/honkit-gen-sample/releases/tag/v3.0.0) Result files
- [refix doc · tsuyoshicho/honkit\-gen\-sample@859de3d](https://github.com/tsuyoshicho/honkit-gen-sample/runs/1301879831?check_suite_focus=true) GitHub workflow log

test and result:
- build step PDF 1st build,PDF 2nd build,EPUB build
- result : PDF fail(1st), PDF seems to be a success(use 1st result svg)

### EPUB fail test result

- [Release Release v4\.0\.1 · tsuyoshicho/honkit\-gen\-sample](https://github.com/tsuyoshicho/honkit-gen-sample/releases/tag/v4.0.1) Result files
- [epub 2 step build · tsuyoshicho/honkit\-gen\-sample@f18348c](https://github.com/tsuyoshicho/honkit-gen-sample/runs/1302009061?check_suite_focus=true) GitHub workflow log

test and result:
- build step EPUB 1st build,EPUB 2nd build,PDF build
- result : EPUB fail(1st), EPUB seems to be a success(use 1st result svg)

### note

PDF and EPUB order change reason, 1st work(e.g. PDF) generate plantuml svg, then 2nd work(e.g. EPUB) success  that is using 1st generated file .

**Comment by azu** [comment]
https://github.com/tsuyoshicho/honkit-gen-sample

I've tried this example.

Success: it can be used as a workaround.

```
rm -rf assets/images/uml/
npm run build # generate *.svg
npm run pdf
```

Failure:

```
rm -rf assets/images/uml/
npm run pdf
```

Probably, [gitbook-plugin-uml](https://github.com/vowstar/gitbook-plugin-uml) generate `*.svg` on [`finish:before`](https://github.com/vowstar/gitbook-plugin-uml/blob/a62baadd97e4fd83bf2a7b4e43476ff4533ceabb/index.js#L119).
However, HonKit copy resources on [generateAssets](https://github.com/honkit/honkit/blob/1ac77dee17c1135b5bbc89f9757f81f93b811c89/packages/honkit/src/output/generateBook.ts#L69).

It is before `finish:before`.

- `generateAssets` → `generatePages` → `finish:before` → `finish`

https://github.com/honkit/honkit/blob/1ac77dee17c1135b5bbc89f9757f81f93b811c89/packages/honkit/src/output/generateBook.ts#L142-L152

On the website, the user can load generated assets in dynamic and it is no problem.
But, `ebook` loading the assets in building(`finish`) time and throw an Error. 

There is some approach to resolve this issue.

1. Build website before Building pdf, epub
    - It is a workaround, but it is easy
2. Add re-copy assets workflow: `finish:before` → `generatePages` → `finish`
   - 📝 `ebook` does copy assets, because that does not include `onAsset`.
https://github.com/honkit/honkit/blob/1ac77dee17c1135b5bbc89f9757f81f93b811c89/packages/honkit/src/output/ebook/index.ts
   -  GitBook did not expected that plugin generate dynamic resources, I think.
3. Fix [gitbook-plugin-uml](https://github.com/vowstar/gitbook-plugin-uml)
   - Generate `*.svg` on `page:before` and it will fix this issue?

**Comment by tsuyoshicho** [comment]
Thanks for research.

I was thought for the plugin(gitbook-plugin-uml) was not made well.

I use this workaround(build).
(And I try fixing slow.)

This issue is a notification and report that there is such a plugin ...

note:
I've try with result.
Windows fail occur (rm -rf asset).

This no problem.
