### ISSUE TITLE
Template escaping doesn't work in included adoc files

### ISSUE THREAD

**Issue by jeff-button** [honkit/honkit#343]
## HonKit version: 4.0.4

I'm using {% raw %} and {% endraw %} in several adoc files.  They are removed correctly by  `honkit build . dist` except when included in another adoc file.

**Parent Adoc**
```
{% raw %} PARENT - this will {{ not be processed }} {% endraw %}

include::./child.adoc[]
```

**Child Adoc**
`{% raw %} CHILD - this will {{ not be processed }} {% endraw %}`

**Html Output**
```html
<pre>PARENT - this will {{ not be processed }}</pre>
<p>{% raw %} CHILD - this will {{ not be processed }} {% endraw %}</p>
```

## Repo
https://github.com/jeff-button/honkitTemplateExample

**Comment by azu** [comment]
Probably, It is caused by the order of processing.
https://github.com/honkit/honkit/blob/b723ce51cf8a4ee1a26a7b8f461c06a650ff7d0c/packages/honkit/src/output/generatePage.ts#L50-L86

Current

1. render template
2. parse markup

`{% raw %}` is processed by template engine. So 1 treat it.
But, `include::./child.adoc[]` is asciidoc feature.
As a result, it can not process `{% raw %}` in child.asoc.

I am not aware if this order can be changed.(It may breaks something)


Workaround: Probably, it can be avoided by using `inclulde` tag.

```
{% include "./child.adoc" %}
```

- https://honkit.netlify.app/templating/conrefs.html

It is processed by template engine.
