### ISSUE TITLE
Error occured of "include file not found" by using asciidoc include directive.

### ISSUE THREAD

**Issue by UsedPartsJapan** [honkit/honkit#356]
## Summary

When using the include directive in an AsciiDoc file, an "include file not found" error occurs.

asciidoctor: ERROR: <stdin>: line 3: include file not found: D:/Document/share/TechnicalSiteGenerator/HonKit/resources/included1.txt
asciidoctor: ERROR: <stdin>: line 8: include file not found: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included2.txt
asciidoctor: ERROR: <stdin>: line 13: include file not found: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included3.txt

- HonKit version: 4.0.8

## Step to reproduce

1. make content1.adoc file like bellow.
```
----
include:: ./resources/included1.txt[]
----
```
2. build 
npx honkit build

- Link to code example:
[sample.zip](https://github.com/honkit/honkit/files/12062830/sample.zip)

## Expected results
This is the included text1 !

## Actual results
Unresolved directive in <stdin> - include::./resources/included1.txt[]

$ npx honkit build --log=debug
debug: readme found at README.adoc
debug: summary file found at SUMMARY.adoc
debug: cleanup folder "Q:\Document\share\TechnicalSiteGenerator\HonKit\_book"
info: 4 plugins are installed
info: 4 explicitly listed
info: plugin "search-pro-fixed" is loaded
info: plugin "highlight" is loaded
info: plugin "fontsettings" is loaded
info: plugin "theme-default" is loaded
info: found 3 pages
info: found 3 asset files
debug: calling hook "config"
debug: calling hook "init"
debug: copy assets from theme Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\@honkit\honkit-plugin-theme-default\_assets\website
debug: copy resources from plugin Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\gitbook-plugin-fontsettings\assets
debug: copy resources from plugin Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\@honkit\honkit-plugin-highlight\css
debug: copy resources from plugin Q:\Document\share\TechnicalSiteGenerator\HonKit\node_modules\gitbook-plugin-search-pro-fixed\assets
debug: copy asset "chapter-1\resources\included1.txt"
debug: copy asset "chapter-1\resources\included2.txt"
debug: copy asset "chapter-1\resources\included3.txt"
debug: calling hook "page:before"
debug: calling hook "page:before"
debug: calling hook "page:before"
asciidoctor: ERROR: <stdin>: line 3: include file not found1: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included1.txt
asciidoctor: ERROR: <stdin>: line 8: include file not found1: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included2.txt
asciidoctor: ERROR: <stdin>: line 13: include file not found1: Q:/Doc
ument/share/TechnicalSiteGenerator/HonKit/resources/included3.txt
debug: calling hook "page"
debug: calling hook "page"
debug: calling hook "page"
debug: index page README.adoc
debug: index page chapter-1/README.adoc
debug: index page chapter-1/content1.adoc
debug: calling hook "finish:before"
debug: calling hook "finish"
debug: write search index
info: >> generation finished with success in 29.6s !

**Comment by azu** [comment]
Thanks for report.

I confirmed it.
It is failed on Windows/Linux.
https://github.com/azu/honkit-issue-356/actions/runs/5564350767/jobs/10163899453

The cause seems to be that the base directory is not taken into account during the conversion.

- Actual: Q:/Document/share/TechnicalSiteGenerator/HonKit/resources/included1.txt
- Expected: Q:/Document/share/TechnicalSiteGenerator/HonKit/docs/chapter-1/resources/included1.txt

```
----
include:: ./docs/chapter-1resources/included1.txt[]
----
```

This will works but is not user-friendly.

📝 I dig it, but it is a bit complex…

I want to pass base directory to these `convert` method.

- https://github.com/honkit/honkit/blob/777bfa43a97925e550a4b2279f39e4778f598120/packages/@honkit/asciidoc/src/toHTML.ts#L6-L13

https://github.com/honkit/honkit/blob/777bfa43a97925e550a4b2279f39e4778f598120/packages/@honkit/asciidoc/src/toHTML.ts#L6-L13
 
Call Stack

- wrap `asciidocToHTML`

https://github.com/honkit/honkit/blob/1a9cbf96860f03237d09e99a3a8dd6bae99d16c3/packages/@honkit/html/src/index.ts#L37-L44

- `toHTML(args[0])` call `asciidocToHTML`

https://github.com/honkit/honkit/blob/1a9cbf96860f03237d09e99a3a8dd6bae99d16c3/packages/@honkit/html/src/index.ts#L22

We need to add second argument for passing base dir.

```js
type AbstractConvertOptions = {
  baseDir: string;
};
function compose(toHTML, fn) {
    return function WRAP_TO_HTML(content: string, options: AbstractConvertOptions) {
        const args = _.toArray(arguments);
        args[0] = toHTML(content, options);
        return fn.apply(null, args);
    };
}
```

3. pass second args when call the WRAP_TO_HTML function

https://github.com/honkit/honkit/blob/8ba20969474cc52332f75319959d34470988c32a/packages/honkit/src/models/parser.ts#L27-L91

This change will be breaking changes.

### Related

- https://github.com/GitbookIO/gitbook/pull/1733

**Comment by azu** [comment]
This issue is fixed in https://github.com/honkit/honkit/releases/tag/v5.0.0

please try it!
